### Test item netService
GET http://localhost:6002/api/item/test

### Create Item
POST http://localhost:6002/api/item
Content-Type: application/json

{
  "name": "Apple Phone",
  "description": "Good item",
  "amount": "1",
  "price": "100",
  "userId": "1"
}

### Get item
GET http://localhost:6002/api/item?itemId=1

### Get all items
GET http://localhost:6002/api/item/all

### Get all items by user id
GET http://localhost:6002/api/item/all/user?userId=1

### Update Item
PUT http://localhost:6002/api/item?itemId=1
Content-Type: application/json

{
  "name": "Banana Phone",
  "description": "Good item",
  "amount": "1",
  "price": "100",
  "userId": "2"
}

### Buy item
GET http://localhost:6002/api/item/buy?itemId=1

### Delete item
DELETE http://localhost:6002/api/item?itemId=1

### Microservice Support
### Get item details
GET http://localhost:6002/api/item/support?itemId=1